version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - terraform --version
  build:
    commands:
      - terraform init -input=false
      - terraform validate
      - terraform plan -out=myplan
      - cp myplan ../myplan
  post_build:
    commands:
      - echo "Check The TF plan Artifacts"
      - 
     
artifacts:
   files:
      - myplan